### PR TITLE
Update deprecated gradle properties and libray dependency

### PR DESCRIPTION
**Pull request by xavier-figueroa**
commons-lang:2.6 is deprecated
baseName has been replaced for archiveBaseName
classifier has been replaced for archiveClassifier
username and password values needs to be passed as string to avoid compilation errors

Project can be run without any changes now :)
@dpolivaev could you take a look please?

### CODE REVIEW

**Comment by dpolivaev** [comment]
I have just fixed the gradle 8 compatibility issues.
I am not sure if we should update  commons-lang:2.6 to version 3 because I am not sure if they are compatible and which version is used in Freeplane.

The following block is correct, it contains credentials needed to upload the component to maven central which are made available as gradle properties and obviously not checked in.

`````
                username ossrhUsername
                password ossrhPassword
`````

**Comment by xavier-figueroa** [comment]
Im getting this issue when I try to build the project
```
A problem occurred evaluating root project 'shtml'.
> Could not get unknown property 'ossrhUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.
```
I had to put in quotes both the password and username in order to fix it
I'm using gradle 8.2.1 and also tested with 8.1

Regarding the library, I can do a research on that if you want

**Comment by dpolivaev** [comment]
Just add the following two lines to your default gradle.properties:

`````
ossrhUsername=user
ossrhPassword=password
`````

**Comment by dpolivaev** [comment]
You can add this information to the project README

**Pull request closed without merging**
